### ISSUE TITLE
problems installing cytoscape angular

### ISSUE THREAD

**Issue by Marianna1989** [michaelbushe/cytoscape-angular#1]
Hello, I am having problems installing the library. I followed the steps in the doc but when I try to run the code in VS code, some files are missing. I created the missing files, based on the files in github but I receive a code error. How can I install cytoscape library for Angular 10?
Thank you.

**Comment by michaelbushe** [comment]
Hi Marianna, my apologies for the slow response, just seeing this today.

I don't use VSCode but do include WebStorm config files.

Did you install the angular-cli?
Did you run:
npm install

Please indicate the error messages so I can help you better.

**Comment by mmestas** [comment]
I'm also getting errors... One problem that I can identify is the references to primeng in cytoscap-angular.js 
when I changed the references from 
`import { ButtonModule, DropdownModule, FieldsetModule, InputSwitchModule, InputTextModule, OverlayPanelModule, ProgressBarModule, TooltipModule, SpinnerModule } from 'primeng';`
to the following:
`import { ButtonModule } from 'primeng/button';
import { DropdownModule } from 'primeng/dropdown';
import { FieldsetModule } from 'primeng/fieldset';
import { InputSwitchModule } from 'primeng/inputswitch';
import { InputTextModule } from 'primeng/inputtext';
import { OverlayPanelModule } from 'primeng/overlaypanel';
import { ProgressBarModule } from 'primeng/progressbar';
import { ProgressSpinnerModule } from 'primeng/progressspinner';
import { TooltipModule } from 'primeng/tooltip';
import { SpinnerModule } from 'primeng/spinner';`

as individual component references, the error that I was getting "primeg does not have exported module ButtonModule...." cleared up, but now I'm getting:
`Error: Cannot resolve type entity i3.ScrollingModule to symbol
    at Object.reflectTypeEntityToDeclaration (/Users/monettem/dev/design/telestra-ui-kit/node_modules/@angular/compiler-cli/src/ngtsc/reflection/src/typescript.js:483:19)`
    
    These errors only appear when I try to add the CytoscapeAngularModule to my project.  As soon as I take it out, the errors clear up.

**Comment by michaelbushe** [comment]
Let me see how best to resolve this. For sure the biggest pain I had in making this project is with primeng (and it's not really a necessary dependency).  Please upload your files (minus node_modules) if you get a chance.  Meanwhile, I'll try to make a new directory that you can just copy to make a new project (or maybe an Angular schematic to run.)

**Comment by michaelbushe** [comment]
I upgraded everything to Angular 12 (using the latest npm, 7.19.1 and ng 12.1.2) and released 0.8.1, I hope this helps.  I'm trying to create a separate example but I'm still having trouble importing cytoscape-angular (WS will say it's not there but still show the doc for it in the same popup).

**Comment by michaelbushe** [comment]
Now we are up to 0.8.6.  It's not working but very close I think someone can get the example working.  The only problem seems to be at runtime:
"cytoscape is not defined"

Cytoscape.js has been included via this in app.component.ts:
declare var cytoscape: any

I supposed this is no longer the way to include js in Angular 12.

**Comment by michaelbushe** [comment]
Note that there's a new top-level dir called ./example-project.  The intent is to just copy that directory to start your new project and start coding.

**Comment by michaelbushe** [comment]
Now up to 0.8.12, this one removed the demo project leaving the example-project that should make it easy to copy and go.  Let me know if that works for you.  The nice menus from the buttons are pretty wonky right now primeng theme didn't make their newest version so there are still some changes to make if you want the toolbars that confugure the graph, but the graph component itself is in working order.
