### ISSUE TITLE
Unable to run example project - Script file "node_modules/cytoscape/dist/cytoscape.min.js" does not exist.

### ISSUE THREAD

**Issue by codycodes** [michaelbushe/cytoscape-angular#5]
Hi, I'm new to Angular dev and would love to use this component! I looked through the issues and couldn't figure out what I need to do to get the example project built though. Apparently there's a missing minified js file? Maybe I need to run a command or add an option to generate the required files? It's important for me to be able to have something simple to build this project off of; just a single command would be great to build and run the project! For now I will elect to just use cytoscape.js in my project, but I would love to get up and running with this component in the future! Thanks for building this component!
 
 ```
 $ npm run build

> cytoscape-angular-example@0.8.12 build /home/codes/clone/cytoscape-angular/example-project
> ng build

⠋ Generating browser application bundles (phase: setup)...An unhandled exception occurred: Script file node_modules/cytoscape/dist/cytoscape.min.js does not exist.
```

**Comment by michaelbushe** [comment]
Did you run npm install first?

**Comment by codycodes** [comment]
Hey Michael, thanks for your response; much appreciated. Yep, ran `npm install` but most likely was just having an issue with the directory I was running it in or some other issue that I'm not remembering the context for. I don't think others are necessarily facing the same issue I did so I'll go ahead and close this. Thanks again!
